/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author alunos
 */
public class CadastrarVeiculo_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarVeículo_GUI
     */
    public CadastrarVeiculo_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new org.edisoncor.gui.panel.Panel();
        jPanel1 = new javax.swing.JPanel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        placa_txt = new javax.swing.JTextField();
        modelo_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cor_txt = new javax.swing.JComboBox();
        CADASTRAR_BTN = new org.edisoncor.gui.button.ButtonNice();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel3 = new org.edisoncor.gui.panel.Panel();
        cpf_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panel4 = new org.edisoncor.gui.panel.Panel();
        tipoVaga_txt = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        tipoVeiculo_txt = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        VOLTARMENU = new javax.swing.JMenuItem();
        VOLTARTABELA = new javax.swing.JMenuItem();

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        panelCurves1.setLayout(null);

        panel1.setBackground(new java.awt.Color(51, 0, 102));
        panel1.setForeground(new java.awt.Color(51, 0, 204));
        panel1.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel1.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MODELO DO VEÍCULO:");
        panel1.add(jLabel1);
        jLabel1.setBounds(10, 100, 250, 32);

        placa_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        panel1.add(placa_txt);
        placa_txt.setBounds(270, 50, 330, 31);

        modelo_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        panel1.add(modelo_txt);
        modelo_txt.setBounds(270, 100, 330, 31);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("COR DO VEÍCULO:");
        panel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 210, 32);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PLACA DO VEÍCULO:");
        panel1.add(jLabel6);
        jLabel6.setBounds(10, 50, 224, 32);

        cor_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cor_txt.setMaximumRowCount(4);
        cor_txt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Branco", "Preto", "Prata", "Vermelho", "Azul", "Amarelo", "Verde", "Laranja", "Marrom", "Bege", "Dourado", "Roxo", "Rosa" }));
        panel1.add(cor_txt);
        cor_txt.setBounds(270, 150, 330, 30);

        panelCurves1.add(panel1);
        panel1.setBounds(30, 200, 620, 220);

        CADASTRAR_BTN.setBackground(new java.awt.Color(0, 102, 255));
        CADASTRAR_BTN.setForeground(new java.awt.Color(255, 255, 255));
        CADASTRAR_BTN.setText("CADASTRAR");
        CADASTRAR_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CADASTRAR_BTN.setSegundoColor(new java.awt.Color(51, 102, 255));
        CADASTRAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTRAR_BTNActionPerformed(evt);
            }
        });
        panelCurves1.add(CADASTRAR_BTN);
        CADASTRAR_BTN.setBounds(700, 430, 220, 30);

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/VEICULO-ICONE.png"))); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelCurves1.add(panelImage1);
        panelImage1.setBounds(800, 20, 100, 100);

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastre as informações do VEÍCULO");
        panelCurves1.add(jLabel4);
        jLabel4.setBounds(30, 80, 410, 32);

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 45)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tech Solutions S.A.");
        panelCurves1.add(jLabel7);
        jLabel7.setBounds(30, 20, 387, 61);

        panel3.setBackground(new java.awt.Color(51, 0, 102));
        panel3.setForeground(new java.awt.Color(51, 0, 204));
        panel3.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel3.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel3.setLayout(null);

        cpf_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        panel3.add(cpf_txt);
        cpf_txt.setBounds(430, 10, 320, 31);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CPF DO REPRESENTANTE: ");
        panel3.add(jLabel8);
        jLabel8.setBounds(130, 10, 290, 32);

        panelCurves1.add(panel3);
        panel3.setBounds(30, 140, 890, 50);

        panel4.setBackground(new java.awt.Color(51, 0, 102));
        panel4.setForeground(new java.awt.Color(51, 0, 204));
        panel4.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel4.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel4.setLayout(null);

        tipoVaga_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        tipoVaga_txt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COLABORADOR", "VISITANTE", "CARGA/DESCARGA" }));
        panel4.add(tipoVaga_txt);
        tipoVaga_txt.setBounds(20, 70, 220, 30);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("TIPO DE VEÍCULO:");
        panel4.add(jLabel9);
        jLabel9.setBounds(20, 110, 210, 32);

        tipoVeiculo_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 17)); // NOI18N
        tipoVeiculo_txt.setMaximumRowCount(4);
        tipoVeiculo_txt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CARRO", "MOTO", "CAMINHONETE" }));
        panel4.add(tipoVeiculo_txt);
        tipoVeiculo_txt.setBounds(20, 150, 220, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIPO DE VAGA:");
        panel4.add(jLabel2);
        jLabel2.setBounds(20, 30, 224, 32);

        panelCurves1.add(panel4);
        panel4.setBounds(660, 200, 260, 220);

        jPanel1.add(panelCurves1);
        panelCurves1.setBounds(0, 0, 950, 500);

        jMenu1.setForeground(new java.awt.Color(51, 0, 255));
        jMenu1.setText("Sair");
        jMenu1.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N

        VOLTARMENU.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        VOLTARMENU.setForeground(new java.awt.Color(51, 0, 255));
        VOLTARMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow.png"))); // NOI18N
        VOLTARMENU.setText("Voltar para o Menu");
        VOLTARMENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLTARMENUActionPerformed(evt);
            }
        });
        jMenu1.add(VOLTARMENU);

        VOLTARTABELA.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        VOLTARTABELA.setForeground(new java.awt.Color(51, 0, 255));
        VOLTARTABELA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow.png"))); // NOI18N
        VOLTARTABELA.setText("Voltar para a Tabela");
        VOLTARTABELA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLTARTABELAActionPerformed(evt);
            }
        });
        jMenu1.add(VOLTARTABELA);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(954, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VOLTARMENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTARMENUActionPerformed
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTARMENUActionPerformed

    private void VOLTARTABELAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTARTABELAActionPerformed
        new VisualizarVeiculo_GUI().setVisible(true);
        Controller.TABELA_DAO.refreshVeiculo();
        this.dispose();
    }//GEN-LAST:event_VOLTARTABELAActionPerformed

    private void CADASTRAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTRAR_BTNActionPerformed
        Controller.VEICULO_DAO.cadastrarVeiculo();
    }//GEN-LAST:event_CADASTRAR_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarVeiculo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarVeiculo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarVeiculo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarVeiculo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarVeiculo_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonNice CADASTRAR_BTN;
    private javax.swing.JMenuItem VOLTARMENU;
    private javax.swing.JMenuItem VOLTARTABELA;
    public static javax.swing.JComboBox cor_txt;
    public static javax.swing.JTextField cpf_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField modelo_txt;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    public static javax.swing.JTextField placa_txt;
    public static javax.swing.JComboBox tipoVaga_txt;
    public static javax.swing.JComboBox tipoVeiculo_txt;
    // End of variables declaration//GEN-END:variables
}
