/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.ImageIcon;

/**
 *
 * @author alunos
 */
public class CadastrarVisitante_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarVeículo_GUI
     */
    public CadastrarVisitante_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new org.edisoncor.gui.panel.Panel();
        jPanel1 = new javax.swing.JPanel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        panel3 = new org.edisoncor.gui.panel.Panel();
        cpf_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jLabel3 = new javax.swing.JLabel();
        nome_txt = new javax.swing.JTextField();
        motivo_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        colaborador_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        empresa_txt = new javax.swing.JTextField();
        CADASTRAR_BTN = new org.edisoncor.gui.button.ButtonNice();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        panel4 = new org.edisoncor.gui.panel.Panel();
        foto_img = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        SELECIONAR_BTN = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        VOLTARMENU_BTN = new javax.swing.JMenuItem();
        VOLTARTABELA_BTN = new javax.swing.JMenuItem();

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        panelCurves1.setLayout(null);

        panel3.setBackground(new java.awt.Color(51, 0, 102));
        panel3.setForeground(new java.awt.Color(51, 0, 204));
        panel3.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel3.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel3.setLayout(null);

        cpf_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        panel3.add(cpf_txt);
        cpf_txt.setBounds(400, 10, 320, 33);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CPF DO USUÁRIO: ");
        panel3.add(jLabel1);
        jLabel1.setBounds(170, 10, 220, 32);

        panelCurves1.add(panel3);
        panel3.setBounds(30, 130, 890, 50);

        panel1.setBackground(new java.awt.Color(51, 0, 102));
        panel1.setForeground(new java.awt.Color(51, 0, 204));
        panel1.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel1.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMPRESA REPRESENTANTE:");
        panel1.add(jLabel3);
        jLabel3.setBounds(10, 80, 314, 32);

        nome_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        panel1.add(nome_txt);
        nome_txt.setBounds(320, 30, 330, 33);

        motivo_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        motivo_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motivo_txtActionPerformed(evt);
            }
        });
        panel1.add(motivo_txt);
        motivo_txt.setBounds(320, 130, 330, 33);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MOTIVO DA VISITA: ");
        panel1.add(jLabel5);
        jLabel5.setBounds(10, 130, 236, 32);

        colaborador_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        colaborador_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaborador_txtActionPerformed(evt);
            }
        });
        panel1.add(colaborador_txt);
        colaborador_txt.setBounds(320, 180, 330, 33);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NOME COMPLETO: ");
        panel1.add(jLabel8);
        jLabel8.setBounds(10, 30, 226, 32);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("NOME DO COLABORADOR: ");
        panel1.add(jLabel9);
        jLabel9.setBounds(10, 180, 321, 32);

        empresa_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        empresa_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresa_txtActionPerformed(evt);
            }
        });
        panel1.add(empresa_txt);
        empresa_txt.setBounds(320, 80, 330, 33);

        panelCurves1.add(panel1);
        panel1.setBounds(30, 190, 670, 240);

        CADASTRAR_BTN.setBackground(new java.awt.Color(0, 102, 255));
        CADASTRAR_BTN.setForeground(new java.awt.Color(255, 255, 255));
        CADASTRAR_BTN.setText("CADASTRAR");
        CADASTRAR_BTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CADASTRAR_BTN.setSegundoColor(new java.awt.Color(51, 102, 255));
        CADASTRAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTRAR_BTNActionPerformed(evt);
            }
        });
        panelCurves1.add(CADASTRAR_BTN);
        CADASTRAR_BTN.setBounds(700, 440, 220, 30);

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastre as informações do VISITANTE");
        panelCurves1.add(jLabel4);
        jLabel4.setBounds(30, 80, 460, 32);

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 45)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tech Solutions S.A.");
        panelCurves1.add(jLabel7);
        jLabel7.setBounds(30, 20, 411, 61);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/USUARIO-ICONE.png"))); // NOI18N

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelCurves1.add(panelImage2);
        panelImage2.setBounds(800, 20, 100, 100);

        panel4.setBackground(new java.awt.Color(51, 0, 102));
        panel4.setForeground(new java.awt.Color(51, 0, 204));
        panel4.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel4.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel4.setLayout(null);

        foto_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout foto_imgLayout = new javax.swing.GroupLayout(foto_img);
        foto_img.setLayout(foto_imgLayout);
        foto_imgLayout.setHorizontalGroup(
            foto_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        foto_imgLayout.setVerticalGroup(
            foto_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        panel4.add(foto_img);
        foto_img.setBounds(30, 50, 150, 140);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FOTO:");
        panel4.add(jLabel2);
        jLabel2.setBounds(70, 10, 70, 32);

        SELECIONAR_BTN.setText("SELECIONAR");
        SELECIONAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELECIONAR_BTNActionPerformed(evt);
            }
        });
        panel4.add(SELECIONAR_BTN);
        SELECIONAR_BTN.setBounds(50, 200, 110, 25);

        panelCurves1.add(panel4);
        panel4.setBounds(710, 190, 210, 240);

        jPanel1.add(panelCurves1);
        panelCurves1.setBounds(0, 0, 950, 500);

        jMenu1.setForeground(new java.awt.Color(51, 0, 255));
        jMenu1.setText("Sair");
        jMenu1.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N

        VOLTARMENU_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        VOLTARMENU_BTN.setForeground(new java.awt.Color(51, 0, 255));
        VOLTARMENU_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow.png"))); // NOI18N
        VOLTARMENU_BTN.setText("Voltar para o Menu");
        VOLTARMENU_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLTARMENU_BTNActionPerformed(evt);
            }
        });
        jMenu1.add(VOLTARMENU_BTN);

        VOLTARTABELA_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        VOLTARTABELA_BTN.setForeground(new java.awt.Color(51, 0, 255));
        VOLTARTABELA_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow.png"))); // NOI18N
        VOLTARTABELA_BTN.setText("Voltar para a Tabela");
        VOLTARTABELA_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLTARTABELA_BTNActionPerformed(evt);
            }
        });
        jMenu1.add(VOLTARTABELA_BTN);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(950, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VOLTARMENU_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTARMENU_BTNActionPerformed
       new Menu_GUI().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_VOLTARMENU_BTNActionPerformed

    private void VOLTARTABELA_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTARTABELA_BTNActionPerformed
        new VisualizarVisitantes_GUI().setVisible(true);
        Controller.TABELA_DAO.refreshVisitante();
        this.dispose();
    }//GEN-LAST:event_VOLTARTABELA_BTNActionPerformed

    private void motivo_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motivo_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motivo_txtActionPerformed

    private void colaborador_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaborador_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colaborador_txtActionPerformed

    private void empresa_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresa_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresa_txtActionPerformed

    private void SELECIONAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELECIONAR_BTNActionPerformed
        Controller.VISITANTE_DAO.imagem();
        foto_img.setIcon(new ImageIcon(Controller.VISITANTE_DAO.caminhoArquivo));
    }//GEN-LAST:event_SELECIONAR_BTNActionPerformed

    private void CADASTRAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTRAR_BTNActionPerformed
        Controller.VISITANTE_DAO.cadastrarVisitante();
        foto_img.setIcon(new ImageIcon(Controller.VISITANTE_DAO.caminhoArquivo));
    }//GEN-LAST:event_CADASTRAR_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarVisitante_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarVisitante_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarVisitante_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarVisitante_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarVisitante_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonNice CADASTRAR_BTN;
    public static javax.swing.JButton SELECIONAR_BTN;
    private javax.swing.JMenuItem VOLTARMENU_BTN;
    private javax.swing.JMenuItem VOLTARTABELA_BTN;
    public static javax.swing.JTextField colaborador_txt;
    public static javax.swing.JTextField cpf_txt;
    public static javax.swing.JTextField empresa_txt;
    private org.edisoncor.gui.panel.PanelImage foto_img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField motivo_txt;
    public static javax.swing.JTextField nome_txt;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    // End of variables declaration//GEN-END:variables
}
