/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.VISITANTE_DAO;

/**
 *
 * @author alunos
 */
public class Menu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Menu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        CADASTRARVISITANTE_BTN = new javax.swing.JMenuItem();
        VERVISITANTES_BTN = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        CADASTRARVEICULO_BTN = new javax.swing.JMenuItem();
        VERVEICULO_BTN = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        SAIR_BTN = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCurves1.setBackground(new java.awt.Color(51, 0, 153));
        panelCurves1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bem-vindo, Admin!");
        panelCurves1.add(jLabel2);
        jLabel2.setBounds(560, 270, 220, 30);

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 47)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tech Solutions S.A.");
        panelCurves1.add(jLabel4);
        jLabel4.setBounds(460, 200, 520, 81);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        panelCurves1.add(jLabel1);
        jLabel1.setBounds(-290, 50, 1065, 750);

        jPanel1.add(panelCurves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 500);

        jMenuBar1.setForeground(new java.awt.Color(102, 0, 0));

        jMenu2.setForeground(new java.awt.Color(51, 0, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/visitante.png"))); // NOI18N
        jMenu2.setText("Visitante");
        jMenu2.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N

        CADASTRARVISITANTE_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        CADASTRARVISITANTE_BTN.setForeground(new java.awt.Color(51, 0, 255));
        CADASTRARVISITANTE_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AddPessoa.png"))); // NOI18N
        CADASTRARVISITANTE_BTN.setText("Cadastrar Visitantes");
        CADASTRARVISITANTE_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTRARVISITANTE_BTNActionPerformed(evt);
            }
        });
        jMenu2.add(CADASTRARVISITANTE_BTN);

        VERVISITANTES_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        VERVISITANTES_BTN.setForeground(new java.awt.Color(51, 0, 255));
        VERVISITANTES_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/olho.png"))); // NOI18N
        VERVISITANTES_BTN.setText("Visualizar Visitantes");
        VERVISITANTES_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERVISITANTES_BTNActionPerformed(evt);
            }
        });
        jMenu2.add(VERVISITANTES_BTN);

        jMenuBar1.add(jMenu2);

        jMenu3.setForeground(new java.awt.Color(51, 0, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/carroAzul.png"))); // NOI18N
        jMenu3.setText("Estacionamento");
        jMenu3.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N

        CADASTRARVEICULO_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        CADASTRARVEICULO_BTN.setForeground(new java.awt.Color(51, 0, 255));
        CADASTRARVEICULO_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/car plus.png"))); // NOI18N
        CADASTRARVEICULO_BTN.setText("Cadastrar Veículos");
        CADASTRARVEICULO_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CADASTRARVEICULO_BTNActionPerformed(evt);
            }
        });
        jMenu3.add(CADASTRARVEICULO_BTN);

        VERVEICULO_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        VERVEICULO_BTN.setForeground(new java.awt.Color(51, 0, 255));
        VERVEICULO_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/olho.png"))); // NOI18N
        VERVEICULO_BTN.setText("Visualizar Veículos");
        VERVEICULO_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VERVEICULO_BTNActionPerformed(evt);
            }
        });
        jMenu3.add(VERVEICULO_BTN);

        jMenuBar1.add(jMenu3);

        jMenu1.setForeground(new java.awt.Color(51, 0, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow.png"))); // NOI18N
        jMenu1.setText("Sair");
        jMenu1.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N

        SAIR_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        SAIR_BTN.setForeground(new java.awt.Color(51, 0, 255));
        SAIR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow.png"))); // NOI18N
        SAIR_BTN.setText("Sair da conta");
        SAIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIR_BTNActionPerformed(evt);
            }
        });
        jMenu1.add(SAIR_BTN);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(951, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SAIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIR_BTNActionPerformed
        new Inicio_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SAIR_BTNActionPerformed

    private void CADASTRARVISITANTE_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTRARVISITANTE_BTNActionPerformed
        new CadastrarVisitante_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CADASTRARVISITANTE_BTNActionPerformed

    private void VERVISITANTES_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERVISITANTES_BTNActionPerformed
        new VisualizarVisitantes_GUI().setVisible(true);
        Controller.TABELA_DAO.refreshVisitante();
        this.dispose();
    }//GEN-LAST:event_VERVISITANTES_BTNActionPerformed

    private void VERVEICULO_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VERVEICULO_BTNActionPerformed
        new VisualizarVeiculo_GUI().setVisible(true);
        Controller.TABELA_DAO.refreshVeiculo();
        this.dispose();
    }//GEN-LAST:event_VERVEICULO_BTNActionPerformed

    private void CADASTRARVEICULO_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CADASTRARVEICULO_BTNActionPerformed
        new CadastrarVeiculo_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CADASTRARVEICULO_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CADASTRARVEICULO_BTN;
    private javax.swing.JMenuItem CADASTRARVISITANTE_BTN;
    private javax.swing.JMenuItem SAIR_BTN;
    private javax.swing.JMenuItem VERVEICULO_BTN;
    private javax.swing.JMenuItem VERVISITANTES_BTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    // End of variables declaration//GEN-END:variables
}
