/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alunos
 */
public class VisualizarVisitantes_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CadastroVeiculo_GUI
     */
    public VisualizarVisitantes_GUI() {
        initComponents();
    }
    
    public static DefaultTableModel visitantes(ResultSet rs) {
        try {
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();
            
            columnNames.addElement("CPF");
            columnNames.addElement("Nome");
            columnNames.addElement("Foto");
            columnNames.addElement("Empresa");
            columnNames.addElement("Colaborador");
            columnNames.addElement("Motivo");
            columnNames.addElement("Placa");

            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
            return new DefaultTableModel(rows, columnNames);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTextField9 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ESTACIONAMENTO?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        veiculoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Veiculo v");
        veiculoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : veiculoQuery.getResultList();
        visitanteQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Visitante v");
        visitanteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : visitanteQuery.getResultList();
        entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("estacionamento?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        visitanteQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT v FROM Visitante v");
        visitanteList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : visitanteQuery1.getResultList();
        visitanteQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT v FROM Visitante v");
        visitanteList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : visitanteQuery2.getResultList();
        visitanteQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT v FROM Visitante v");
        visitanteList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : visitanteQuery3.getResultList();
        visitanteQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Visitante v");
        visitanteList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : visitanteQuery4.getResultList();
        visitanteQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Visitante v");
        visitanteList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : visitanteQuery5.getResultList();
        visitanteQuery6 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Visitante v");
        visitanteList6 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : visitanteQuery6.getResultList();
        visitanteQuery7 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Visitante v");
        visitanteList7 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : visitanteQuery7.getResultList();
        entityManager1 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("Estacionamento?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        visitanteQuery8 = java.beans.Beans.isDesignTime() ? null : entityManager1.createQuery("SELECT v FROM Visitante v");
        visitanteList8 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : visitanteQuery8.getResultList();
        jPanel1 = new javax.swing.JPanel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel4 = new javax.swing.JLabel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        nome2_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        motivo2_txt = new javax.swing.JTextField();
        empresa2_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        colaborador2_txt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        cpf2_txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panel3 = new org.edisoncor.gui.panel.Panel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        CONSULTAR_BTN = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        ALTERAR_BTN = new javax.swing.JButton();
        EXCLUIR_BTN = new javax.swing.JButton();
        foto2_img = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVisitantes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        VOLTARMENU_BTN = new javax.swing.JMenu();
        CADASTRAR_BTN = new javax.swing.JMenu();

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("EMPRESA REPRESENTANTE:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        panelCurves1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tech Solutions S.A.");
        panelCurves1.add(jLabel4);
        jLabel4.setBounds(20, 20, 387, 61);

        panel1.setBackground(new java.awt.Color(51, 0, 102));
        panel1.setForeground(new java.awt.Color(51, 0, 204));
        panel1.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel1.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel1.setLayout(null);

        nome2_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        nome2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome2_txtActionPerformed(evt);
            }
        });
        panel1.add(nome2_txt);
        nome2_txt.setBounds(20, 40, 390, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MOTIVO DA VISITA:");
        panel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 210, 32);

        motivo2_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        motivo2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motivo2_txtActionPerformed(evt);
            }
        });
        panel1.add(motivo2_txt);
        motivo2_txt.setBounds(20, 100, 390, 30);

        empresa2_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        empresa2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresa2_txtActionPerformed(evt);
            }
        });
        panel1.add(empresa2_txt);
        empresa2_txt.setBounds(20, 160, 390, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOME:");
        panel1.add(jLabel6);
        jLabel6.setBounds(20, 10, 210, 25);

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NOME DO COLABORADOR:");
        panel1.add(jLabel15);
        jLabel15.setBounds(20, 190, 250, 32);

        colaborador2_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        colaborador2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaborador2_txtActionPerformed(evt);
            }
        });
        panel1.add(colaborador2_txt);
        colaborador2_txt.setBounds(20, 220, 390, 30);

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("EMPRESA REPRESENTANTE:");
        panel1.add(jLabel19);
        jLabel19.setBounds(20, 130, 250, 32);

        panelCurves1.add(panel1);
        panel1.setBounds(620, 180, 430, 260);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Visitantes Cadastrados no Estacionamento");
        panelCurves1.add(jLabel2);
        jLabel2.setBounds(20, 80, 461, 32);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("----------- ALTERAR ----------");
        panelCurves1.add(jLabel7);
        jLabel7.setBounds(650, 150, 240, 25);

        panel2.setBackground(new java.awt.Color(51, 0, 102));
        panel2.setForeground(new java.awt.Color(51, 0, 204));
        panel2.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel2.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel2.setLayout(null);

        cpf2_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 20)); // NOI18N
        cpf2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf2_txtActionPerformed(evt);
            }
        });
        panel2.add(cpf2_txt);
        cpf2_txt.setBounds(10, 40, 190, 30);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CPF:");
        panel2.add(jLabel8);
        jLabel8.setBounds(10, 10, 180, 25);

        panel3.setBackground(new java.awt.Color(51, 0, 102));
        panel3.setForeground(new java.awt.Color(51, 0, 204));
        panel3.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel3.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel3.setLayout(null);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panel3.add(jTextField5);
        jTextField5.setBounds(20, 50, 250, 30);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CPF:");
        panel3.add(jLabel9);
        jLabel9.setBounds(20, 80, 40, 32);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panel3.add(jTextField6);
        jTextField6.setBounds(20, 110, 250, 30);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        panel3.add(jTextField7);
        jTextField7.setBounds(20, 170, 250, 30);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MODELO DO VEÍCULO");
        panel3.add(jLabel10);
        jLabel10.setBounds(20, 140, 250, 32);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PLACA DO VEÍCULO:");
        panel3.add(jLabel11);
        jLabel11.setBounds(20, 20, 180, 25);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("COR DO VEÍCULO:");
        panel3.add(jLabel12);
        jLabel12.setBounds(20, 200, 250, 32);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        panel3.add(jTextField8);
        jTextField8.setBounds(20, 230, 250, 30);

        panel2.add(panel3);
        panel3.setBounds(590, 130, 290, 300);

        CONSULTAR_BTN.setBackground(new java.awt.Color(0, 0, 204));
        CONSULTAR_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        CONSULTAR_BTN.setForeground(new java.awt.Color(255, 255, 255));
        CONSULTAR_BTN.setText(">");
        CONSULTAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAR_BTNActionPerformed(evt);
            }
        });
        panel2.add(CONSULTAR_BTN);
        CONSULTAR_BTN.setBounds(210, 40, 50, 30);

        panelCurves1.add(panel2);
        panel2.setBounds(620, 70, 270, 80);

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 3, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("----------- CONSULTAR ----------");
        panelCurves1.add(jLabel13);
        jLabel13.setBounds(640, 40, 240, 25);

        ALTERAR_BTN.setBackground(new java.awt.Color(0, 0, 204));
        ALTERAR_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        ALTERAR_BTN.setForeground(new java.awt.Color(255, 255, 255));
        ALTERAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/alterarPessoa.png"))); // NOI18N
        ALTERAR_BTN.setText("ALTERAR");
        ALTERAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTERAR_BTNActionPerformed(evt);
            }
        });
        panelCurves1.add(ALTERAR_BTN);
        ALTERAR_BTN.setBounds(650, 450, 200, 30);

        EXCLUIR_BTN.setBackground(new java.awt.Color(204, 0, 0));
        EXCLUIR_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        EXCLUIR_BTN.setForeground(new java.awt.Color(255, 255, 255));
        EXCLUIR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        EXCLUIR_BTN.setText("EXCLUIR");
        EXCLUIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_BTNActionPerformed(evt);
            }
        });
        panelCurves1.add(EXCLUIR_BTN);
        EXCLUIR_BTN.setBounds(860, 450, 160, 31);

        foto2_img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Foto*");

        javax.swing.GroupLayout foto2_imgLayout = new javax.swing.GroupLayout(foto2_img);
        foto2_img.setLayout(foto2_imgLayout);
        foto2_imgLayout.setHorizontalGroup(
            foto2_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foto2_imgLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        foto2_imgLayout.setVerticalGroup(
            foto2_imgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foto2_imgLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        panelCurves1.add(foto2_img);
        foto2_img.setBounds(900, 30, 150, 140);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, visitanteList8, tabelaVisitantes);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliCpf}"));
        columnBinding.setColumnName("CPF");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliNome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliFoto}"));
        columnBinding.setColumnName("Foto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliEmpresa}"));
        columnBinding.setColumnName("Empresa");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliColaborador}"));
        columnBinding.setColumnName("Colaborador");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliMotivo}"));
        columnBinding.setColumnName("Motivo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cliPlaca}"));
        columnBinding.setColumnName("Placa");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tabelaVisitantes);

        panelCurves1.add(jScrollPane2);
        jScrollPane2.setBounds(20, 120, 590, 360);

        jPanel1.add(panelCurves1);
        panelCurves1.setBounds(0, 0, 1080, 520);

        jMenuBar1.setForeground(new java.awt.Color(102, 0, 0));

        jMenu4.setForeground(new java.awt.Color(51, 0, 255));
        jMenu4.setText("Sair");
        jMenu4.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });

        VOLTARMENU_BTN.setForeground(new java.awt.Color(51, 0, 255));
        VOLTARMENU_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow.png"))); // NOI18N
        VOLTARMENU_BTN.setText("Voltar Para o Menu");
        VOLTARMENU_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        VOLTARMENU_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLTARMENU_BTNMouseClicked(evt);
            }
        });
        jMenu4.add(VOLTARMENU_BTN);

        jMenuBar1.add(jMenu4);

        CADASTRAR_BTN.setForeground(new java.awt.Color(51, 0, 255));
        CADASTRAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AddPessoa.png"))); // NOI18N
        CADASTRAR_BTN.setText("Cadastrar");
        CADASTRAR_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        CADASTRAR_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CADASTRAR_BTNMouseClicked(evt);
            }
        });
        jMenuBar1.add(CADASTRAR_BTN);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1074, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CADASTRAR_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CADASTRAR_BTNMouseClicked
        new CadastrarVisitante_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CADASTRAR_BTNMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void VOLTARMENU_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLTARMENU_BTNMouseClicked
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VOLTARMENU_BTNMouseClicked

    private void nome2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome2_txtActionPerformed

    private void motivo2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motivo2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motivo2_txtActionPerformed

    private void empresa2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresa2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresa2_txtActionPerformed

    private void cpf2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf2_txtActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void colaborador2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaborador2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colaborador2_txtActionPerformed

    private void CONSULTAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAR_BTNActionPerformed
        Controller.VISITANTE_DAO.consultarVisitante();
        Controller.TABELA_DAO.refreshVisitante();
    }//GEN-LAST:event_CONSULTAR_BTNActionPerformed

    private void ALTERAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTERAR_BTNActionPerformed
        Controller.VISITANTE_DAO.alterarVisitante();
        Controller.TABELA_DAO.refreshVisitante();
    }//GEN-LAST:event_ALTERAR_BTNActionPerformed

    private void EXCLUIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_BTNActionPerformed
        Controller.VISITANTE_DAO.excluirVisitante();
        Controller.TABELA_DAO.refreshVisitante();
    }//GEN-LAST:event_EXCLUIR_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarVisitantes_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarVisitantes_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarVisitantes_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarVisitantes_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarVisitantes_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ALTERAR_BTN;
    private javax.swing.JMenu CADASTRAR_BTN;
    public static javax.swing.JButton CONSULTAR_BTN;
    public static javax.swing.JButton EXCLUIR_BTN;
    private javax.swing.JMenu VOLTARMENU_BTN;
    public static javax.swing.JTextField colaborador2_txt;
    public static javax.swing.JTextField cpf2_txt;
    public static javax.swing.JTextField empresa2_txt;
    private javax.persistence.EntityManager entityManager;
    private javax.persistence.EntityManager entityManager0;
    private javax.persistence.EntityManager entityManager1;
    public static org.edisoncor.gui.panel.PanelImage foto2_img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    public static javax.swing.JTextField motivo2_txt;
    public static javax.swing.JTextField nome2_txt;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    public static javax.swing.JTable tabelaVisitantes;
    private java.util.List<Model.Veiculo> veiculoList;
    private javax.persistence.Query veiculoQuery;
    private java.util.List<Model.Visitante> visitanteList;
    private java.util.List<Model.Visitante> visitanteList1;
    private java.util.List<Model.Visitante> visitanteList2;
    private java.util.List<Model.Visitante> visitanteList3;
    private java.util.List<Model.Visitante> visitanteList4;
    private java.util.List<Model.Visitante> visitanteList5;
    private java.util.List<Model.Visitante> visitanteList6;
    private java.util.List<Model.Visitante> visitanteList7;
    private java.util.List<Model.Visitante> visitanteList8;
    private javax.persistence.Query visitanteQuery;
    private javax.persistence.Query visitanteQuery1;
    private javax.persistence.Query visitanteQuery2;
    private javax.persistence.Query visitanteQuery3;
    private javax.persistence.Query visitanteQuery4;
    private javax.persistence.Query visitanteQuery5;
    private javax.persistence.Query visitanteQuery6;
    private javax.persistence.Query visitanteQuery7;
    private javax.persistence.Query visitanteQuery8;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
