/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import static Controller.VEICULO_DAO.password;
import static Controller.VEICULO_DAO.url;
import static Controller.VEICULO_DAO.username;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Model.Veiculo;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alunos
 */
public class VisualizarVeiculo_GUI extends javax.swing.JFrame {

    /**
     * Creates new form CadastroVeiculo_GUI
     */
    public VisualizarVeiculo_GUI() {
        initComponents();
    }

    public static DefaultTableModel veiculo(ResultSet rs) {
        try {
            ResultSetMetaData metaData = rs.getMetaData();
            int numberOfColumns = metaData.getColumnCount();
            Vector columnNames = new Vector();

            columnNames.addElement("Status");
            columnNames.addElement("Placa");
            columnNames.addElement("Cor");
            columnNames.addElement("Tipo");
            columnNames.addElement("Vaga");
            columnNames.addElement("Modelo");
            columnNames.addElement("Entrada");
            columnNames.addElement("Saida");
            columnNames.addElement("CPF");

            Vector rows = new Vector();
            while (rs.next()) {
                Vector newRow = new Vector();
                for (int i = 1; i <= numberOfColumns; i++) {
                    newRow.addElement(rs.getObject(i));
                }
                rows.addElement(newRow);
            }
            return new DefaultTableModel(rows, columnNames);
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("ESTACIONAMENTO?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        veiculoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Veiculo v");
        veiculoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : veiculoQuery.getResultList();
        entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("estacionamento?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        veiculoQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT v FROM Veiculo v");
        veiculoList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : veiculoQuery1.getResultList();
        veiculoQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT v FROM Veiculo v");
        veiculoList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : veiculoQuery2.getResultList();
        veiculoQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Veiculo v");
        veiculoList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : veiculoQuery3.getResultList();
        veiculoQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT v FROM Veiculo v");
        veiculoList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : veiculoQuery4.getResultList();
        jPanel1 = new javax.swing.JPanel();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel3 = new org.edisoncor.gui.panel.Panel();
        jLabel12 = new javax.swing.JLabel();
        placa3_txt = new javax.swing.JTextField();
        modelo2_txt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panel4 = new org.edisoncor.gui.panel.Panel();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cor2_txt = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        tipoVaga2_txt = new javax.swing.JComboBox();
        tipoVeiculo2_txt = new javax.swing.JComboBox();
        panel1 = new org.edisoncor.gui.panel.Panel();
        placa2_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        CONSULTAR_BTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        EXCLUIR_BTN = new javax.swing.JButton();
        SAIDA_BTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaVeiculos = new javax.swing.JTable();
        ALTERAR_BTN = new javax.swing.JButton();
        RETORNO_BTN = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        Cadastrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setLayout(null);

        panelCurves1.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tech Solutions S.A.");
        panelCurves1.add(jLabel4);
        jLabel4.setBounds(20, 20, 387, 61);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Veículos Cadastrados no Estacionamento");
        panelCurves1.add(jLabel2);
        jLabel2.setBounds(20, 80, 445, 32);

        panel3.setBackground(new java.awt.Color(51, 0, 102));
        panel3.setForeground(new java.awt.Color(51, 0, 204));
        panel3.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel3.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel3.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PLACA DO VEÍCULO:");
        panel3.add(jLabel12);
        jLabel12.setBounds(20, 130, 170, 32);

        placa3_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        placa3_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa3_txtActionPerformed(evt);
            }
        });
        panel3.add(placa3_txt);
        placa3_txt.setBounds(20, 160, 380, 30);

        modelo2_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        modelo2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelo2_txtActionPerformed(evt);
            }
        });
        panel3.add(modelo2_txt);
        modelo2_txt.setBounds(20, 220, 380, 30);

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("MODELO DO VEÍCULO");
        panel3.add(jLabel13);
        jLabel13.setBounds(20, 190, 250, 30);

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("COR DO VEÍCULO:");
        panel3.add(jLabel15);
        jLabel15.setBounds(20, 10, 250, 32);

        panel4.setBackground(new java.awt.Color(51, 0, 102));
        panel4.setForeground(new java.awt.Color(51, 0, 204));
        panel4.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel4.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel4.setLayout(null);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        panel4.add(jTextField13);
        jTextField13.setBounds(20, 50, 250, 30);

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("CPF:");
        panel4.add(jLabel16);
        jLabel16.setBounds(20, 80, 40, 32);

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        panel4.add(jTextField14);
        jTextField14.setBounds(20, 110, 250, 30);

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        panel4.add(jTextField15);
        jTextField15.setBounds(20, 170, 250, 30);

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("MODELO DO VEÍCULO");
        panel4.add(jLabel17);
        jLabel17.setBounds(20, 140, 250, 32);

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("PLACA DO VEÍCULO:");
        panel4.add(jLabel18);
        jLabel18.setBounds(20, 20, 180, 25);

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("COR DO VEÍCULO:");
        panel4.add(jLabel19);
        jLabel19.setBounds(20, 200, 250, 32);

        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        panel4.add(jTextField16);
        jTextField16.setBounds(20, 230, 250, 30);

        panel3.add(panel4);
        panel4.setBounds(590, 130, 290, 300);

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("TIPO DE VEÍCULO:");
        panel3.add(jLabel20);
        jLabel20.setBounds(20, 70, 250, 32);

        cor2_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        cor2_txt.setMaximumRowCount(4);
        cor2_txt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Branco", "Preto", "Prata", "Vermelho", "Azul", "Amarelo", "Verde", "Laranja", "Marrom", "Bege", "Dourado", "Roxo", "Rosa" }));
        panel3.add(cor2_txt);
        cor2_txt.setBounds(20, 40, 210, 30);

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("TIPO DE VAGA:");
        panel3.add(jLabel21);
        jLabel21.setBounds(240, 70, 130, 32);

        tipoVaga2_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        tipoVaga2_txt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COLABORADOR", "VISITANTE", "CARGA/DESCARGA" }));
        tipoVaga2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoVaga2_txtActionPerformed(evt);
            }
        });
        panel3.add(tipoVaga2_txt);
        tipoVaga2_txt.setBounds(240, 100, 160, 30);

        tipoVeiculo2_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        tipoVeiculo2_txt.setMaximumRowCount(4);
        tipoVeiculo2_txt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CARRO", "MOTO", "CAMINHONETE" }));
        panel3.add(tipoVeiculo2_txt);
        tipoVeiculo2_txt.setBounds(20, 100, 210, 30);

        panelCurves1.add(panel3);
        panel3.setBounds(620, 170, 430, 270);

        panel1.setBackground(new java.awt.Color(51, 0, 102));
        panel1.setForeground(new java.awt.Color(51, 0, 204));
        panel1.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel1.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel1.setLayout(null);

        placa2_txt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        placa2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa2_txtActionPerformed(evt);
            }
        });
        panel1.add(placa2_txt);
        placa2_txt.setBounds(20, 50, 270, 30);

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PLACA DO VEÍCULO:");
        panel1.add(jLabel6);
        jLabel6.setBounds(20, 20, 180, 25);

        panel2.setBackground(new java.awt.Color(51, 0, 102));
        panel2.setForeground(new java.awt.Color(51, 0, 204));
        panel2.setColorPrimario(new java.awt.Color(51, 0, 153));
        panel2.setColorSecundario(new java.awt.Color(0, 0, 204));
        panel2.setLayout(null);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panel2.add(jTextField5);
        jTextField5.setBounds(20, 50, 250, 30);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CPF:");
        panel2.add(jLabel8);
        jLabel8.setBounds(20, 80, 40, 32);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panel2.add(jTextField6);
        jTextField6.setBounds(20, 110, 250, 30);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        panel2.add(jTextField7);
        jTextField7.setBounds(20, 170, 250, 30);

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MODELO DO VEÍCULO");
        panel2.add(jLabel9);
        jLabel9.setBounds(20, 140, 250, 32);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("PLACA DO VEÍCULO:");
        panel2.add(jLabel10);
        jLabel10.setBounds(20, 20, 180, 25);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("COR DO VEÍCULO:");
        panel2.add(jLabel11);
        jLabel11.setBounds(20, 200, 250, 32);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        panel2.add(jTextField8);
        jTextField8.setBounds(20, 230, 250, 30);

        panel1.add(panel2);
        panel2.setBounds(590, 130, 290, 300);

        CONSULTAR_BTN.setBackground(new java.awt.Color(0, 0, 204));
        CONSULTAR_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        CONSULTAR_BTN.setForeground(new java.awt.Color(255, 255, 255));
        CONSULTAR_BTN.setText(">");
        CONSULTAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONSULTAR_BTNActionPerformed(evt);
            }
        });
        panel1.add(CONSULTAR_BTN);
        CONSULTAR_BTN.setBounds(300, 50, 50, 30);

        panelCurves1.add(panel1);
        panel1.setBounds(640, 40, 370, 100);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 3, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("----------- ALTERAR ----------");
        panelCurves1.add(jLabel3);
        jLabel3.setBounds(720, 140, 240, 25);

        EXCLUIR_BTN.setBackground(new java.awt.Color(204, 0, 0));
        EXCLUIR_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        EXCLUIR_BTN.setForeground(new java.awt.Color(255, 255, 255));
        EXCLUIR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        EXCLUIR_BTN.setText("EXCLUIR");
        EXCLUIR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_BTNActionPerformed(evt);
            }
        });
        panelCurves1.add(EXCLUIR_BTN);
        EXCLUIR_BTN.setBounds(860, 450, 180, 29);

        SAIDA_BTN.setBackground(new java.awt.Color(0, 153, 51));
        SAIDA_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        SAIDA_BTN.setForeground(new java.awt.Color(255, 255, 255));
        SAIDA_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/saidaVeiculo.png"))); // NOI18N
        SAIDA_BTN.setText("CONFIRMAR SAÍDA");
        SAIDA_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAIDA_BTNActionPerformed(evt);
            }
        });
        panelCurves1.add(SAIDA_BTN);
        SAIDA_BTN.setBounds(80, 450, 230, 29);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 3, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("----------- CONSULTAR ----------");
        panelCurves1.add(jLabel5);
        jLabel5.setBounds(710, 10, 240, 25);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, veiculoList4, tabelaVeiculos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${veiStatus}"));
        columnBinding.setColumnName("Status");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${veiPlaca}"));
        columnBinding.setColumnName("Placa");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${veiCor}"));
        columnBinding.setColumnName("Cor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${veiTipo}"));
        columnBinding.setColumnName("Tipo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${veiVaga}"));
        columnBinding.setColumnName("Vaga");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${veiModelo}"));
        columnBinding.setColumnName("Modelo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${veiEntrada}"));
        columnBinding.setColumnName("Entrada");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${veiSaida}"));
        columnBinding.setColumnName("Saida");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${veiCpf}"));
        columnBinding.setColumnName("CPF");
        columnBinding.setColumnClass(Long.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tabelaVeiculos);

        panelCurves1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 130, 590, 310);

        ALTERAR_BTN.setBackground(new java.awt.Color(0, 0, 204));
        ALTERAR_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        ALTERAR_BTN.setForeground(new java.awt.Color(255, 255, 255));
        ALTERAR_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/alterarCarro.png"))); // NOI18N
        ALTERAR_BTN.setText("ALTERAR");
        ALTERAR_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALTERAR_BTNActionPerformed(evt);
            }
        });
        panelCurves1.add(ALTERAR_BTN);
        ALTERAR_BTN.setBounds(630, 450, 200, 29);

        RETORNO_BTN.setBackground(new java.awt.Color(153, 153, 0));
        RETORNO_BTN.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        RETORNO_BTN.setForeground(new java.awt.Color(255, 255, 255));
        RETORNO_BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/retornoVeiculo.png"))); // NOI18N
        RETORNO_BTN.setText("CONFIRMAR RETORNO");
        RETORNO_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETORNO_BTNActionPerformed(evt);
            }
        });
        panelCurves1.add(RETORNO_BTN);
        RETORNO_BTN.setBounds(330, 450, 230, 29);

        jPanel1.add(panelCurves1);
        panelCurves1.setBounds(0, 0, 1080, 520);

        jMenuBar1.setForeground(new java.awt.Color(102, 0, 0));

        jMenu4.setForeground(new java.awt.Color(51, 0, 255));
        jMenu4.setText("Sair");
        jMenu4.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        jMenuItem1.setForeground(new java.awt.Color(51, 0, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/arrow.png"))); // NOI18N
        jMenuItem1.setText("Voltar para o Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        Cadastrar.setForeground(new java.awt.Color(51, 0, 255));
        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/car plus.png"))); // NOI18N
        Cadastrar.setText("Cadastrar");
        Cadastrar.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        Cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Cadastrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1074, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void CadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMouseClicked
        new CadastrarVeiculo_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CadastrarMouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void placa2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placa2_txtActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void placa3_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa3_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placa3_txtActionPerformed

    private void modelo2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelo2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelo2_txtActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Menu_GUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tipoVaga2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoVaga2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoVaga2_txtActionPerformed

    private void CONSULTAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONSULTAR_BTNActionPerformed
        Controller.VEICULO_DAO.consultarVeiculo();
        Controller.TABELA_DAO.refreshVeiculo();
    }//GEN-LAST:event_CONSULTAR_BTNActionPerformed

    private void ALTERAR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALTERAR_BTNActionPerformed
        Controller.VEICULO_DAO.alterarVeiculo();
        Controller.TABELA_DAO.refreshVeiculo();
    }//GEN-LAST:event_ALTERAR_BTNActionPerformed

    private void EXCLUIR_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_BTNActionPerformed
        Controller.VEICULO_DAO.excluirVeiculo();
        Controller.TABELA_DAO.refreshVeiculo();
    }//GEN-LAST:event_EXCLUIR_BTNActionPerformed

    private void SAIDA_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAIDA_BTNActionPerformed
        Controller.VEICULO_DAO.registrarSaida();
        Controller.TABELA_DAO.refreshVeiculo();
    }//GEN-LAST:event_SAIDA_BTNActionPerformed

    private void RETORNO_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETORNO_BTNActionPerformed
        Controller.VEICULO_DAO.registrarRetorno();
        Controller.TABELA_DAO.refreshVeiculo();
    }//GEN-LAST:event_RETORNO_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarVeiculo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarVeiculo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarVeiculo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarVeiculo_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarVeiculo_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALTERAR_BTN;
    private javax.swing.JButton CONSULTAR_BTN;
    private javax.swing.JMenu Cadastrar;
    private javax.swing.JButton EXCLUIR_BTN;
    private javax.swing.JButton RETORNO_BTN;
    private javax.swing.JButton SAIDA_BTN;
    public static javax.swing.JComboBox cor2_txt;
    private javax.persistence.EntityManager entityManager;
    private javax.persistence.EntityManager entityManager0;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    public static javax.swing.JTextField modelo2_txt;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    public static javax.swing.JTextField placa2_txt;
    public static javax.swing.JTextField placa3_txt;
    public static javax.swing.JTable tabelaVeiculos;
    public static javax.swing.JComboBox tipoVaga2_txt;
    public static javax.swing.JComboBox tipoVeiculo2_txt;
    private java.util.List<Model.Veiculo> veiculoList;
    private java.util.List<Model.Veiculo> veiculoList1;
    private java.util.List<Model.Veiculo> veiculoList2;
    private java.util.List<Model.Veiculo> veiculoList3;
    private java.util.List<Model.Veiculo> veiculoList4;
    private javax.persistence.Query veiculoQuery;
    private javax.persistence.Query veiculoQuery1;
    private javax.persistence.Query veiculoQuery2;
    private javax.persistence.Query veiculoQuery3;
    private javax.persistence.Query veiculoQuery4;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
